/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.*;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;



/**
 *
 * @author Raja Gopal V
 */
public class BookingForm extends javax.swing.JFrame {

    /**
     * Creates new form BookingForm
     */
    public BookingForm() {
        initComponents();
        
        dateField.removeAllItems();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        for(int i=0; i<7; i++){
            LocalDate futureDate = LocalDate.now().plusDays(i);
            String formattedDate = futureDate.format(formatter);
            dateField.addItem(formattedDate);
        }

        serviceField.removeAllItems();
        serviceField.addItem("Oil Change");
        serviceField.addItem("Engine Check");
        serviceField.addItem("Brake Repair");
        serviceField.addItem("AC Service");
        serviceField.addItem("Full Inspection");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vehiclenoField = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nameField = new javax.swing.JTextField();
        brandField = new javax.swing.JTextField();
        versionField = new javax.swing.JTextField();
        dateField = new javax.swing.JComboBox<>();
        serviceField = new javax.swing.JComboBox<>();
        backBtn = new javax.swing.JButton();
        bookBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1000, 700));
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FixIt");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Service Booking");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Number");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 122, -1, -1));
        getContentPane().add(vehiclenoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, 172, -1));

        searchBtn.setBackground(new java.awt.Color(204, 153, 0));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 174, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Version");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 229, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Brand");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 287, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 343, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Service");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 422, -1, -1));
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 174, 172, -1));
        getContentPane().add(brandField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 285, 172, -1));

        versionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                versionFieldActionPerformed(evt);
            }
        });
        getContentPane().add(versionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 229, 172, -1));

        dateField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        dateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(dateField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 343, 172, -1));

        serviceField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        getContentPane().add(serviceField, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 422, 172, -1));

        backBtn.setBackground(new java.awt.Color(204, 153, 0));
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(51, 51, 51));
        backBtn.setText("Back");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 522, -1, -1));

        bookBtn.setBackground(new java.awt.Color(204, 153, 0));
        bookBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bookBtn.setForeground(new java.awt.Color(51, 51, 51));
        bookBtn.setText("Book");
        bookBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 522, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/book (2).png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        String vehicleNo = vehiclenoField.getText().trim();
        
        if(vehicleNo.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a Vehicle Number.");
            return;
        }
        
        try{
            Connection conn = db.DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM vehicles_details WHERE vehicle_no = ?");
            ps.setString(1, vehicleNo);
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                
                // Autofill only these fields
                nameField.setText(rs.getString("name"));
                versionField.setText(rs.getString("version"));
                brandField.setText(rs.getString("brand"));   
                
            }else{
                JOptionPane.showMessageDialog(this, "No vehicle found with that number.");
            }
            
            rs.close();
            ps.close();
            conn.close();
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void versionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_versionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_versionFieldActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        new HomeForm().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void dateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dateFieldActionPerformed

    private void bookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBtnActionPerformed
        String vehicleNo = vehiclenoField.getText().trim();
        String name = nameField.getText().trim();
        String version = versionField.getText().trim();
        String brand = brandField.getText().trim();
        String formattedDate;
        SimpleDateFormat fromUser = new SimpleDateFormat("dd-MM-yyyy");
        SimpleDateFormat toDatabase = new SimpleDateFormat("yyyy-MM-dd");
        String service = serviceField.getSelectedItem().toString();
        
        String formatted = "";
        try{
            formattedDate = new SimpleDateFormat("yyyy-MM-dd").format(new SimpleDateFormat("dd-MM-yyyy").parse(dateField.getSelectedItem().toString()));
        } catch(ParseException e){
            JOptionPane.showMessageDialog(this, "Invalid date format");
            return;
        }
        if(vehicleNo.isEmpty()||name.isEmpty()||version.isEmpty()||brand.isEmpty()||formattedDate.isEmpty()||service.isEmpty()){
            JOptionPane.showMessageDialog(this, "Please fill all fields before booking.");
            return;
        }
        
        try{
            Connection conn = db.DBConnection.getConnection();
            PreparedStatement ps = conn.prepareStatement("INSERT INTO bookings(vehicle_no, name, version, brand, date, service) VALUES (?, ?, ?, ?, ?, ?)");
            ps.setString(1, vehicleNo);
            ps.setString(2, name);
            ps.setString(3, version);
            ps.setString(4, brand);
            ps.setString(5, formattedDate);
            ps.setString(6, service);
            
            int i = ps.executeUpdate();
            if(i > 0){
                JOptionPane.showMessageDialog(this, "Your Appointment has been successfully booked.");
                new BookingList().setVisible(true);
                this.dispose();
            }
            
            ps.close();
            conn.close();
        } catch (Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }
    }//GEN-LAST:event_bookBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookingForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookingForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JButton bookBtn;
    private javax.swing.JTextField brandField;
    private javax.swing.JComboBox<String> dateField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> serviceField;
    private javax.swing.JTextField vehiclenoField;
    private javax.swing.JTextField versionField;
    // End of variables declaration//GEN-END:variables
}
