/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
/**
 *
 * @author Raja Gopal V
 */
public class DeleteForm extends javax.swing.JFrame {

    /**
     * Creates new form DeleteForm
     */
    public DeleteForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        yomField = new javax.swing.JTextField();
        brandField = new javax.swing.JTextField();
        versionField = new javax.swing.JTextField();
        avehicleField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        evehiclenoField = new javax.swing.JTextField();
        deleteBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("FixIt");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Vehicle Detail Delete Page");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 167, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 248, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vehicle No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 329, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Version");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 410, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Brand");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 501, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Year of Manufacture");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 580, -1, -1));

        backBtn.setBackground(new java.awt.Color(204, 153, 0));
        backBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(386, 635, -1, -1));
        getContentPane().add(yomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 580, 220, -1));
        getContentPane().add(brandField, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 501, 220, -1));
        getContentPane().add(versionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 410, 220, -1));
        getContentPane().add(avehicleField, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 329, 220, -1));
        getContentPane().add(nameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 248, 220, -1));
        getContentPane().add(evehiclenoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 167, 220, -1));

        deleteBtn.setBackground(new java.awt.Color(204, 153, 0));
        deleteBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(479, 635, -1, -1));

        searchBtn.setBackground(new java.awt.Color(204, 153, 0));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        searchBtn.setText("Search");
        searchBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 165, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Log_imresizer.jpg"))); // NOI18N
        jLabel10.setText("jLabel8");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            Connection conn = db.DBConnection.getConnection();
            String sql = "SELECT * FROM vehicles_details WHERE vehicle_no=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, evehiclenoField.getText());
            
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                nameField.setText(rs.getString("name"));
                avehicleField.setText(rs.getString("vehicle_no"));
                versionField.setText(rs.getString("version"));
                brandField.setText(rs.getString("brand"));
                yomField.setText(rs.getString("year_of_manufacture"));
            } else{
                JOptionPane.showMessageDialog(null, "Vehicle not found!");
            }
            
            conn.close();
        } catch (SQLException ex) {
            Logger.getLogger(DeleteForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        try{
            Connection conn = db.DBConnection.getConnection();
            String sql = "DELETE FROM vehicles_details WHERE vehicle_no =?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, evehiclenoField.getText());
            
            int rowsDeleted = ps.executeUpdate();
            if(rowsDeleted > 0){
                JOptionPane.showMessageDialog(null, "Vehicle Detail deleted sucessfully!");
                
                nameField.setText("");
                avehicleField.setText("");
                versionField.setText("");
                brandField.setText("");
                yomField.setText("");
            } else {
                JOptionPane.showMessageDialog(null, "Delete failed. Vehicle not found.");
            }
            
            conn.close();
        } catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        HomeForm home = new HomeForm();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField avehicleField;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField brandField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField evehiclenoField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nameField;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField versionField;
    private javax.swing.JTextField yomField;
    // End of variables declaration//GEN-END:variables
}
