/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author Raja Gopal V
 */
public class HomeForm extends javax.swing.JFrame {

    /**
     * Creates new form HomeForm
     */
    public HomeForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        drBtn = new javax.swing.JButton();
        vlBtn = new javax.swing.JButton();
        uBtn = new javax.swing.JButton();
        lBtn = new javax.swing.JButton();
        bBtn = new javax.swing.JButton();
        osbBtn = new javax.swing.JButton();
        dBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FixIt");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 39, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/homelogo.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 143, -1, -1));

        drBtn.setBackground(new java.awt.Color(204, 153, 0));
        drBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        drBtn.setText("Details Reg");
        drBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        drBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drBtnActionPerformed(evt);
            }
        });
        getContentPane().add(drBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 143, -1, -1));

        vlBtn.setBackground(new java.awt.Color(204, 153, 0));
        vlBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        vlBtn.setText(" View List");
        vlBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        vlBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vlBtnActionPerformed(evt);
            }
        });
        getContentPane().add(vlBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 282, -1, -1));

        uBtn.setBackground(new java.awt.Color(204, 153, 0));
        uBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        uBtn.setText("Update");
        uBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        uBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uBtnActionPerformed(evt);
            }
        });
        getContentPane().add(uBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 442, -1, -1));

        lBtn.setBackground(new java.awt.Color(204, 153, 0));
        lBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        lBtn.setText("Logout");
        lBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lBtnActionPerformed(evt);
            }
        });
        getContentPane().add(lBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(606, 607, -1, -1));

        bBtn.setBackground(new java.awt.Color(204, 153, 0));
        bBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        bBtn.setText("Booking");
        bBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBtnActionPerformed(evt);
            }
        });
        getContentPane().add(bBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 205, -1, -1));

        osbBtn.setBackground(new java.awt.Color(204, 153, 0));
        osbBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        osbBtn.setText("Onspot Booking");
        osbBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        osbBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                osbBtnActionPerformed(evt);
            }
        });
        getContentPane().add(osbBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 356, -1, -1));

        dBtn.setBackground(new java.awt.Color(204, 153, 0));
        dBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        dBtn.setText("Delete");
        dBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        dBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBtnActionPerformed(evt);
            }
        });
        getContentPane().add(dBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(717, 511, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/homebg2.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void vlBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vlBtnActionPerformed
        BookingList vlBtn = new BookingList();
        vlBtn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_vlBtnActionPerformed

    private void bBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBtnActionPerformed
        BookingForm bBtn = new BookingForm();
        bBtn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_bBtnActionPerformed

    private void drBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drBtnActionPerformed
        Vehicle_RegistrationForm drBtn = new Vehicle_RegistrationForm();
        drBtn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_drBtnActionPerformed

    private void osbBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_osbBtnActionPerformed
        OnspotForm osbBtn = new OnspotForm();
        osbBtn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_osbBtnActionPerformed

    private void uBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uBtnActionPerformed
        UpdateForm uBtn = new UpdateForm();
        uBtn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_uBtnActionPerformed

    private void dBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBtnActionPerformed
        DeleteForm dBtn = new DeleteForm();
        dBtn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_dBtnActionPerformed

    private void lBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lBtnActionPerformed
        LoginForm lBtn = new LoginForm();
        lBtn.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bBtn;
    private javax.swing.JButton dBtn;
    private javax.swing.JButton drBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lBtn;
    private javax.swing.JButton osbBtn;
    private javax.swing.JButton uBtn;
    private javax.swing.JButton vlBtn;
    // End of variables declaration//GEN-END:variables
}
