/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Raja Gopal V
 */
public class UpdateForm extends javax.swing.JFrame {

    /**
     * Creates new form DeleteForm
     */
    public UpdateForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        uyomField = new javax.swing.JTextField();
        ubrandField = new javax.swing.JTextField();
        uversionField = new javax.swing.JTextField();
        uvehiclenoField = new javax.swing.JTextField();
        unameField = new javax.swing.JTextField();
        ovehiclenoField = new javax.swing.JTextField();
        fetchBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setText("FixIt");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel2.setText("Vehicle Details Update Page");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 80, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Old Vehicle No");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 175, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Updated Name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 238, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Updated Vehicle No");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 313, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Updated Version");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 388, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Updated Brand");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 468, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Updated Year of Manufacture");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(288, 544, -1, -1));
        getContentPane().add(uyomField, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 544, 220, -1));
        getContentPane().add(ubrandField, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 468, 220, -1));

        uversionField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uversionFieldActionPerformed(evt);
            }
        });
        getContentPane().add(uversionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 388, 220, -1));

        uvehiclenoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uvehiclenoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(uvehiclenoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 313, 220, -1));

        unameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(unameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 238, 220, -1));

        ovehiclenoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ovehiclenoFieldActionPerformed(evt);
            }
        });
        getContentPane().add(ovehiclenoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 175, 220, -1));

        fetchBtn.setBackground(new java.awt.Color(204, 153, 0));
        fetchBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        fetchBtn.setText("Fetch");
        fetchBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        fetchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fetchBtnActionPerformed(evt);
            }
        });
        getContentPane().add(fetchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(815, 173, -1, -1));

        updateBtn.setBackground(new java.awt.Color(204, 153, 0));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        updateBtn.setText("Update");
        updateBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        getContentPane().add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(553, 622, -1, -1));

        homeBtn.setBackground(new java.awt.Color(204, 153, 0));
        homeBtn.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(437, 622, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Log_imresizer.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ovehiclenoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ovehiclenoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ovehiclenoFieldActionPerformed

    private void unameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unameFieldActionPerformed

    private void uvehiclenoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uvehiclenoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uvehiclenoFieldActionPerformed

    private void uversionFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uversionFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_uversionFieldActionPerformed

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        HomeForm home = new HomeForm();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void fetchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fetchBtnActionPerformed
        try {
            Connection conn = db.DBConnection.getConnection();
            String sql = "SELECT * FROM vehicles_details WHERE vehicle_no = ?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, ovehiclenoField.getText());
            
            ResultSet rs = ps.executeQuery();
            if(rs.next()){
                unameField.setText(rs.getString("name"));
                uvehiclenoField.setText(rs.getString("vehicle_no"));
                uversionField.setText(rs.getString("version"));
                ubrandField.setText(rs.getString("brand"));
                uyomField.setText(rs.getString("year_of_manufacture"));
            } else {
                JOptionPane.showMessageDialog(null, "Vehicle not found!");
            }
            
            conn.close();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_fetchBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        try {
            Connection conn = db.DBConnection.getConnection();
            String sql = "UPDATE vehicles_details SET name=?, vehicle_no=?, version=?, brand=?, year_of_manufacture=? WHERE vehicle_no=?";
            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, unameField.getText());
            ps.setString(2, uvehiclenoField.getText());
            ps.setString(3, uversionField.getText());
            ps.setString(4, ubrandField.getText());
            ps.setString(5, uyomField.getText());
            ps.setString(6, ovehiclenoField.getText());
            
            int rowsUpdated = ps.executeUpdate();
            if(rowsUpdated > 0) {
                JOptionPane.showMessageDialog(null, "Record updated sucessfully!");
            } else {
                 JOptionPane.showMessageDialog(null, "Update failed. Vehicle not found.");
            }
            
            conn.close();
        } catch(Exception ex){
            ex.printStackTrace();
        }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton fetchBtn;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField ovehiclenoField;
    private javax.swing.JTextField ubrandField;
    private javax.swing.JTextField unameField;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField uvehiclenoField;
    private javax.swing.JTextField uversionField;
    private javax.swing.JTextField uyomField;
    // End of variables declaration//GEN-END:variables
}
